server {
    listen 80;

    # This root sends e.g.
    # http://localhost/index.html -> /usr/share/nginx/html/index.html
    root /usr/share/nginx/html;
    # This index sends e.g.
    # http://localhost/ -> /usr/share/nginx/html -> /usr/share/nginx/html/index.html
    index index.html;

    # Try the exact file (/index.html)
    # Try directory (/index.html/)
    # Otherwise return 404
    location / {
        try_files $uri $uri/ =404;
    }
}