# Rate limiting (simple protection layer)
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

# Load balancing group for app1
upstream app1_cluster {
    server app1a:8000;
    server app1b:8000;
}

server {
    listen 80;

    # -------------------------
    # ROUTING
    # -------------------------

    location /app1/ {
        limit_req zone=api_limit;

        proxy_pass http://app1_cluster;
    }

    location /app2/ {
        limit_req zone=api_limit;

        proxy_pass http://app2:8000;
    }
}